package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1



/**
 * Bedel generated by hbm2java
 */
public class Bedel extends Usuario implements java.io.Serializable {


     private String nickusuario;
     private Usuario usuario;
     private String turno;

    public Bedel() {
        super();
    }

	
    public Bedel(Usuario usuario) {
        this.usuario = usuario;
    }
    public Bedel(Usuario usuario, String turno) {
       this.usuario = usuario;
       this.turno = turno;
    }
    public Bedel(String nickUsuario,String nombre,String apellido, String turno) {
       super(nickUsuario,nombre,apellido);
       this.turno = turno;
    }
   
    
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }




}


