package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clave generated by hbm2java
 */
public class Clave  implements java.io.Serializable {


     private int idclave;
     private Politicadeseguridad politicadeseguridad;
     private Usuario usuario;
     private Bedel bedel;
     private String claveactual;
     private Date fechamodificacion;

    public Clave() {
    }

	
    public Clave(int idclave, Politicadeseguridad politicadeseguridad) {
        this.idclave = idclave;
        this.politicadeseguridad = politicadeseguridad;
    }
    public Clave(int idclave, Politicadeseguridad politicadeseguridad, Usuario usuario, String claveactual, Date fechamodificacion) {
       this.idclave = idclave;
       this.politicadeseguridad = politicadeseguridad;
       this.usuario = usuario;
       this.claveactual = claveactual;
       this.fechamodificacion = fechamodificacion;
    }
    public Clave(Politicadeseguridad ps, Bedel adm, String contrasea, Date mifecha) {
      this.politicadeseguridad = ps;
      this.bedel = adm;
      this.claveactual = contrasea;
      this.fechamodificacion = mifecha;
    }

   
    public int getIdclave() {
        return this.idclave;
    }
    
    public void setIdclave(int idclave) {
        this.idclave = idclave;
    }
    public Politicadeseguridad getPoliticadeseguridad() {
        return this.politicadeseguridad;
    }
    
    public void setPoliticadeseguridad(Politicadeseguridad politicadeseguridad) {
        this.politicadeseguridad = politicadeseguridad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getClaveactual() {
        return this.claveactual;
    }
    
    public void setClaveactual(String claveactual) {
        this.claveactual = claveactual;
    }
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }
    
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }




}


