package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DiareservaId generated by hbm2java
 */
public class DiareservaId  implements java.io.Serializable {


     private int iddiareserva;
     private Date diacalendario;

    public DiareservaId() {
    }

    public DiareservaId(int iddiareserva, Date diacalendario) {
       this.iddiareserva = iddiareserva;
       this.diacalendario = diacalendario;
    }
   
    public int getIddiareserva() {
        return this.iddiareserva;
    }
    
    public void setIddiareserva(int iddiareserva) {
        this.iddiareserva = iddiareserva;
    }
    public Date getDiacalendario() {
        return this.diacalendario;
    }
    
    public void setDiacalendario(Date diacalendario) {
        this.diacalendario = diacalendario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiareservaId) ) return false;
		 DiareservaId castOther = ( DiareservaId ) other; 
         
		 return (this.getIddiareserva()==castOther.getIddiareserva())
 && ( (this.getDiacalendario()==castOther.getDiacalendario()) || ( this.getDiacalendario()!=null && castOther.getDiacalendario()!=null && this.getDiacalendario().equals(castOther.getDiacalendario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIddiareserva();
         result = 37 * result + ( getDiacalendario() == null ? 0 : this.getDiacalendario().hashCode() );
         return result;
   }   


}


