package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Diareserva generated by hbm2java
 */
public class Diareserva  implements java.io.Serializable {


     private DiareservaId id;
     private Aula aula;
     private Reserva reserva;
     private Date horainicio;
     private Date duracion;

    public Diareserva() {
    }

	
    public Diareserva(DiareservaId id, Reserva reserva) {
        this.id = id;
        this.reserva = reserva;
    }
    public Diareserva(DiareservaId id, Aula aula, Reserva reserva, Date horainicio, Date duracion) {
       this.id = id;
       this.aula = aula;
       this.reserva = reserva;
       this.horainicio = horainicio;
       this.duracion = duracion;
    }
   
    public DiareservaId getId() {
        return this.id;
    }
    
    public void setId(DiareservaId id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }




}


