package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1



/**
 * Esporadica generated by hbm2java
 */
public class Esporadica  implements java.io.Serializable {


     private int idreserva;
     private Reserva reserva;

    public Esporadica() {
    }

    public Esporadica(Reserva reserva) {
       this.reserva = reserva;
    }
   
    public int getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(int idreserva) {
        this.idreserva = idreserva;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


