package datos;
// Generated 08/11/2017 00:15:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     String nickusuario;
     private String apellido;
     private String nombre;
     private Set claves = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Admin admin;
     private Bedel bedel;

    public Usuario() {
    }

	
    public Usuario(String nickusuario) {
        this.nickusuario = nickusuario;
    }
    public Usuario(String nickusuario, String apellido, String nombre, Set claves, Set reservas, Admin admin, Bedel bedel) {
       this.nickusuario = nickusuario;
       this.apellido = apellido;
       this.nombre = nombre;
       this.claves = claves;
       this.reservas = reservas;
       this.admin = admin;
       this.bedel = bedel;
    }
   public Usuario(String nickusuario, String apellido, String nombre) {
       this.nickusuario = nickusuario;
       this.apellido = apellido;
       this.nombre = nombre;
       
    }
    public String getNickusuario() {
        return this.nickusuario;
    }
    
    public void setNickusuario(String nickusuario) {
        this.nickusuario = nickusuario;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClaves() {
        return this.claves;
    }
    
    public void setClaves(Set claves) {
        this.claves = claves;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Bedel getBedel() {
        return this.bedel;
    }
    
    public void setBedel(Bedel bedel) {
        this.bedel = bedel;
    }




}


